# Generated by Django 3.2.6 on 2021-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
                ('college', models.CharField(max_length=60)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('P', 'Passout')], max_length=1)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('AI/DS', 'AI/DS'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE')], max_length=5)),
                ('nlp', models.TextField()),
            ],
        ),
    ]
